"""Generate the RTL configuration header and packed weight/bias memories.

Reads model/export/ (produced by model/quantize.py) and emits:

  sim/build/accel_config.svh  -- per-layer tile counts, requant params,
                                 memory sizes (included by accel_top.sv)
  sim/build/weights.mem       -- weights packed in controller streaming order
  sim/build/biases.mem        -- biases packed one output-block per word

Weight packing order (the controller reads this with a single incrementing
pointer -- no address arithmetic in hardware):

  for layer l:                     (output dims padded up to a multiple of N)
    for output block j:            (N output neurons)
      for input tile i:            (N input elements)
        for row r in 0..N-1:
          word = { W[j*N+N-1][i*N+r], ..., W[j*N+0][i*N+r] }   (col 0 = LSB)

Each weights.mem word is N*8 bits: the N weights loaded into one array row
for that tile (one word per w_load cycle). Each biases.mem word is N*32 bits:
the biases for one output block, consumed by the per-column accumulators.

Usage: python sim/gen_config.py [--n 4]
"""

import argparse
import json
import pathlib
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "model"))

from golden import load_mem  # noqa: E402


def pad_out(arr, n, axis=0):
    """Zero-pad the output dimension up to a multiple of n."""
    pad = (-arr.shape[axis]) % n
    if pad == 0:
        return arr
    widths = [(0, 0)] * arr.ndim
    widths[axis] = (0, pad)
    return np.pad(arr, widths)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=4, help="array dimension N")
    args = ap.parse_args()
    n = args.n

    export = ROOT / "model" / "export"
    build = ROOT / "sim" / "build"
    build.mkdir(parents=True, exist_ok=True)

    meta = json.loads((export / "meta.json").read_text())
    dims = meta["layer_dims"]

    w_words, b_words = [], []
    in_tiles, out_blocks = [], []
    for l, (in_f, out_f) in enumerate(dims):
        assert in_f % n == 0, f"layer {l}: in_features {in_f} not divisible by {n}"
        w = load_mem(export / f"layer{l}_w.mem", bits=8).reshape(out_f, in_f)
        b = load_mem(export / f"layer{l}_b.mem", bits=32)
        w = pad_out(w.astype(np.int64), n)          # (out_padded, in)
        b = pad_out(b.astype(np.int64), n)
        n_blk, n_tile = w.shape[0] // n, in_f // n
        out_blocks.append(n_blk)
        in_tiles.append(n_tile)

        for j in range(n_blk):
            for i in range(n_tile):
                for r in range(n):
                    word = 0
                    for c in range(n):
                        word |= (int(w[j * n + c][i * n + r]) & 0xFF) << (8 * c)
                    w_words.append(word)
            word = 0
            for c in range(n):
                word |= (int(b[j * n + c]) & 0xFFFFFFFF) << (32 * c)
            b_words.append(word)

    wdig, bdig = n * 8 // 4, n * 32 // 4
    (build / "weights.mem").write_text(
        "\n".join(format(w, f"0{wdig}x") for w in w_words) + "\n")
    (build / "biases.mem").write_text(
        "\n".join(format(b, f"0{bdig}x") for b in b_words) + "\n")

    def case_fn(name, ret_decl, values):
        lines = [f"function automatic {ret_decl} {name}(input [3:0] l);"]
        lines.append("    case (l)")
        for i, v in enumerate(values):
            lines.append(f"        4'd{i}: {name} = {v};")
        lines.append(f"        default: {name} = 0;")
        lines.append("    endcase")
        lines.append("endfunction")
        return "\n".join(lines)

    nl = len(dims)
    ms = meta["requant_M"] + [0]
    shifts = meta["requant_shift"] + [1]  # shift>=1 keeps rounding term legal
    svh = "\n\n".join([
        "// AUTOGENERATED by sim/gen_config.py -- do not edit.",
        f"localparam int CFG_NUM_LAYERS = {nl};",
        f"localparam int CFG_W_WORDS    = {len(w_words)};",
        f"localparam int CFG_B_WORDS    = {len(b_words)};",
        f"localparam int CFG_ACT_DEPTH  = {max(in_tiles + out_blocks)};",
        case_fn("cfg_in_tiles", "[15:0]", in_tiles),
        case_fn("cfg_out_blocks", "[15:0]", out_blocks),
        case_fn("cfg_m", "signed [15:0]", ms[:nl]),
        case_fn("cfg_shift", "[4:0]", shifts[:nl]),
    ]) + "\n"
    (build / "accel_config.svh").write_text(svh)

    print(f"N={n}: {len(w_words)} weight words, {len(b_words)} bias words")
    print(f"in_tiles={in_tiles} out_blocks={out_blocks}")
    print(f"wrote {build / 'accel_config.svh'}")


if __name__ == "__main__":
    main()
