// Full-system self-checking testbench for accel_top.
//
// Flow (driven by sim/run_sim.py, which generates the expected-value files
// from the Python golden model):
//   1. $readmemh packed weights/biases into the DUT memories.
//   2. Stream batches of real MNIST images in through the image port.
//   3. Run inference; capture the INT32 logit stream.
//   4. Check, per image:
//        - hidden-layer activations (every requantized value, bit-exact)
//        - all 10 logits (bit-exact vs golden)
//        - final prediction vs golden prediction and true label
//   5. Track functional coverage bins and report a coverage %.
//
// Plusargs:
//   +images=K     number of test images to run (default 16)
//   +batch=B      batch size per accelerator run, 1..16 (default 16)
//   +trace=FILE   dump per-cycle JSON trace (use with +images=1 +batch=1)
//   +vcd=FILE     dump VCD waveform

`timescale 1ns / 1ps

module tb_accel;

    parameter  int N = 4;                    // override: iverilog -Ptb_accel.N=8
    localparam int DATA_W = 8, ACC_W = 32, B_MAX = 16;
    localparam int B_ADDR = $clog2(B_MAX);
    localparam int MAX_IMGS = 200;

    `include "accel_config.svh"

    // state encoding must match accel_top's enum order
    localparam int ST_IDLE = 0, ST_SETUP = 1, ST_PRELOAD = 2, ST_RUN = 3,
                   ST_TAIL = 4, ST_REQ = 5, ST_DONE = 6;

    logic clk = 0, rst_n = 0;
    always #5 clk = ~clk;

    logic                     start = 0;
    logic [B_ADDR:0]          batch_size = 1;
    logic                     img_wen = 0;
    logic [B_ADDR-1:0]        img_b = 0;
    logic [9:0]               img_idx = 0;
    logic signed [DATA_W-1:0] img_data = 0;
    wire                      logits_valid;
    wire signed [N*ACC_W-1:0] logits_flat;
    wire  [B_ADDR-1:0]        logits_b;
    wire  [7:0]               logits_base;
    wire                      done;
    wire  [31:0]              cycle_count;

    accel_top #(.N(N), .DATA_W(DATA_W), .ACC_W(ACC_W), .B_MAX(B_MAX)) dut (
        .clk(clk), .rst_n(rst_n), .start(start), .batch_size(batch_size),
        .img_wen(img_wen), .img_b(img_b), .img_idx(img_idx), .img_data(img_data),
        .logits_valid(logits_valid), .logits_flat(logits_flat),
        .logits_b(logits_b), .logits_base(logits_base),
        .done(done), .cycle_count(cycle_count));

    // ------------------------------------------------------------------
    // Stimulus / expected data (generated by sim/run_sim.py + quantize.py)
    // ------------------------------------------------------------------
    logic signed [7:0]  images     [0:MAX_IMGS*784-1];
    logic        [7:0]  labels     [0:MAX_IMGS-1];
    logic signed [31:0] exp_logits [0:MAX_IMGS*10-1];
    logic signed [7:0]  exp_act0   [0:MAX_IMGS*32-1];
    logic signed [7:0]  exp_act1   [0:MAX_IMGS*16-1];

    reg [1023:0] imgfile = "model/export/test_images.mem";
    initial begin
        if ($value$plusargs("imgfile=%s", imgfile)) ;
        $readmemh("sim/build/weights.mem", dut.wmem);
        $readmemh("sim/build/biases.mem", dut.bmem);
        $readmemh(imgfile, images);
        $readmemh("sim/build/labels.mem", labels);
        $readmemh("sim/build/exp_logits.mem", exp_logits);
        $readmemh("sim/build/exp_act0.mem", exp_act0);
        $readmemh("sim/build/exp_act1.mem", exp_act1);
    end

    // ------------------------------------------------------------------
    // Result capture and checking
    // ------------------------------------------------------------------
    integer n_images = 16, batch_arg = 16;
    integer batch_base = 0;             // global index of image 0 of this run
    integer nb = 0;                     // images in current run
    integer act_errors = 0, act_checked = 0;
    integer logit_errors = 0, logit_checked = 0;
    integer pred_match_label = 0, pred_match_golden = 0, results = 0;
    integer total_cycles = 0, runs = 0;

    logic signed [31:0] rtl_logits [0:B_MAX-1][0:9];

    integer ci, gi, k;
    always @(negedge clk) begin
        // hidden-layer activation check (every requantize write, bit-exact)
        if (dut.req_wen_d2 && !(dut.layer == CFG_NUM_LAYERS - 1)) begin
            for (ci = 0; ci < N; ci = ci + 1) begin
                gi = batch_base + dut.req_b_d2;
                if (dut.layer == 0) begin
                    if (dut.req_y[ci] !== exp_act0[gi*32 + dut.out_blk*N + ci])
                        act_errors = act_errors + 1;
                end else begin
                    if (dut.req_y[ci] !== exp_act1[gi*16 + dut.out_blk*N + ci])
                        act_errors = act_errors + 1;
                end
                act_checked = act_checked + 1;
            end
        end
        // logit capture
        if (logits_valid) begin
            if (^logits_flat === 1'bx) begin
                $display("FATAL: X in logits");
                $finish;
            end
            for (ci = 0; ci < N; ci = ci + 1)
                if (logits_base + ci < 10)
                    rtl_logits[logits_b][logits_base + ci]
                        = logits_flat[ci*ACC_W +: ACC_W];
        end
        // protocol assertion: a block is fully drained before its preload
        if ((|dut.drain_valid) && dut.state == ST_PRELOAD) begin
            $display("FATAL: drain during block preload");
            $finish;
        end
    end

    // ------------------------------------------------------------------
    // Functional coverage (manual bins; Icarus has no covergroups)
    // ------------------------------------------------------------------
    integer cov_w_zero = 0, cov_w_pos = 0, cov_w_neg = 0;
    integer cov_w_max = 0, cov_w_min = 0;
    integer cov_act_zero = 0, cov_act_mid = 0, cov_act_max = 0;
    integer cov_req_relu = 0, cov_req_sat = 0, cov_req_mid = 0;
    integer cov_acc_small = 0, cov_acc_med = 0, cov_acc_large = 0, cov_acc_huge = 0;
    integer cov_psum_neg = 0, cov_psum_pos = 0;
    integer cov_batch_1 = 0, cov_batch_max = 0;

    integer wi, wl;
    integer w_tmp, a_tmp, acc_tmp, p_tmp;
    initial begin : cov_weights
        #2;  // after $readmemh
        for (wi = 0; wi < CFG_W_WORDS; wi = wi + 1)
            for (wl = 0; wl < N; wl = wl + 1) begin
                w_tmp = $signed(dut.wmem[wi][wl*DATA_W +: DATA_W]);
                if (w_tmp == 0)         cov_w_zero = cov_w_zero + 1;
                else if (w_tmp > 0)     cov_w_pos  = cov_w_pos + 1;
                else                    cov_w_neg  = cov_w_neg + 1;
                if (w_tmp == 127)       cov_w_max  = cov_w_max + 1;
                if (w_tmp == -127)      cov_w_min  = cov_w_min + 1;
            end
    end

    always @(negedge clk) begin
        if (dut.vec_valid_d)
            for (ci = 0; ci < N; ci = ci + 1) begin
                a_tmp = dut.u_array.a_h[ci][0];
                if (a_tmp == 0)          cov_act_zero = cov_act_zero + 1;
                else if (a_tmp == 127)   cov_act_max  = cov_act_max + 1;
                else                     cov_act_mid  = cov_act_mid + 1;
            end
        for (ci = 0; ci < N; ci = ci + 1)
            if (dut.drain_valid[ci]) begin
                p_tmp = $signed(dut.psum_flat[ci*ACC_W +: ACC_W]);
                if (p_tmp < 0) cov_psum_neg = cov_psum_neg + 1;
                else           cov_psum_pos = cov_psum_pos + 1;
            end
        if (dut.req_wen_d2)
            for (ci = 0; ci < N; ci = ci + 1) begin
                acc_tmp = dut.acc_rdata_d[ci];
                if (!(dut.layer == CFG_NUM_LAYERS - 1)) begin
                    if (acc_tmp < 0)                 cov_req_relu = cov_req_relu + 1;
                    else if (dut.req_y[ci] == 127)   cov_req_sat  = cov_req_sat + 1;
                    else                             cov_req_mid  = cov_req_mid + 1;
                end
                acc_tmp = (acc_tmp < 0) ? -acc_tmp : acc_tmp;
                if (acc_tmp < 128)          cov_acc_small = cov_acc_small + 1;
                else if (acc_tmp < 2048)    cov_acc_med   = cov_acc_med + 1;
                else if (acc_tmp < 32768)   cov_acc_large = cov_acc_large + 1;
                else                        cov_acc_huge  = cov_acc_huge + 1;
            end
    end

    task report_coverage;
        integer hit, total;
        begin
            hit = 0; total = 19;
            hit = hit + (cov_w_zero  > 0) + (cov_w_pos > 0) + (cov_w_neg > 0)
                      + (cov_w_max   > 0) + (cov_w_min > 0)
                      + (cov_act_zero > 0) + (cov_act_mid > 0) + (cov_act_max > 0)
                      + (cov_req_relu > 0) + (cov_req_sat > 0) + (cov_req_mid > 0)
                      + (cov_acc_small > 0) + (cov_acc_med > 0)
                      + (cov_acc_large > 0) + (cov_acc_huge > 0)
                      + (cov_psum_neg > 0) + (cov_psum_pos > 0)
                      + (cov_batch_1 > 0) + (cov_batch_max > 0);
            $display("COVBIN w_zero=%0d w_pos=%0d w_neg=%0d w_max=%0d w_min=%0d",
                     cov_w_zero, cov_w_pos, cov_w_neg, cov_w_max, cov_w_min);
            $display("COVBIN act_zero=%0d act_mid=%0d act_max=%0d",
                     cov_act_zero, cov_act_mid, cov_act_max);
            $display("COVBIN req_relu=%0d req_sat=%0d req_mid=%0d",
                     cov_req_relu, cov_req_sat, cov_req_mid);
            $display("COVBIN acc_small=%0d acc_med=%0d acc_large=%0d acc_huge=%0d",
                     cov_acc_small, cov_acc_med, cov_acc_large, cov_acc_huge);
            $display("COVBIN psum_neg=%0d psum_pos=%0d batch1=%0d batchmax=%0d",
                     cov_psum_neg, cov_psum_pos, cov_batch_1, cov_batch_max);
            $display("COVERAGE hit=%0d total=%0d pct=%0d.%0d",
                     hit, total, (hit * 1000 / total) / 10, (hit * 1000 / total) % 10);
        end
    endtask

    // ------------------------------------------------------------------
    // Per-cycle JSON trace (drives the visualizer)
    // ------------------------------------------------------------------
    integer tfh = 0;
    reg [1023:0] tracefile;
    integer tr, tc;
    initial begin
        if ($value$plusargs("trace=%s", tracefile)) begin
            tfh = $fopen(tracefile, "w");
            if (tfh == 0) begin
                $display("FATAL: cannot open trace file");
                $finish;
            end
        end
    end

    always @(negedge clk) begin
        if (tfh != 0 && rst_n && dut.state != ST_IDLE) begin
            $fwrite(tfh, "{\"c\":%0d,\"st\":%0d,\"l\":%0d,\"t\":%0d,\"j\":%0d,\"pe\":[",
                    cycle_count, dut.state, dut.layer, dut.in_tile, dut.out_blk);
            for (tr = 0; tr < N; tr = tr + 1) begin
                if (tr != 0) $fwrite(tfh, ",");
                $fwrite(tfh, "[");
                for (tc = 0; tc < N; tc = tc + 1) begin
                    if (tc != 0) $fwrite(tfh, ",");
                    $fwrite(tfh, "{\"a\":%0d,\"w\":%0d,\"p\":%0d}",
                            dut.u_array.a_h[tr][tc],
                            dut.u_array.w_dbg[tr][tc],
                            dut.u_array.psum_v[tr+1][tc]);
                end
                $fwrite(tfh, "]");
            end
            $fwrite(tfh, "],\"dv\":%0d,\"acc\":[%0d,%0d,%0d,%0d]",
                    dut.drain_valid,
                    dut.g_acc[0].u_acc.mem[0], dut.g_acc[1].u_acc.mem[0],
                    dut.g_acc[2].u_acc.mem[0], dut.g_acc[3].u_acc.mem[0]);
            if (dut.req_wen_d2)
                $fwrite(tfh, ",\"req\":{\"b\":%0d,\"y\":[%0d,%0d,%0d,%0d],\"acc\":[%0d,%0d,%0d,%0d]}",
                        dut.req_b_d2,
                        dut.req_y[0], dut.req_y[1], dut.req_y[2], dut.req_y[3],
                        dut.acc_rdata_d[0], dut.acc_rdata_d[1],
                        dut.acc_rdata_d[2], dut.acc_rdata_d[3]);
            $fwrite(tfh, "}\n");
        end
    end

    // ------------------------------------------------------------------
    // Main sequence
    // ------------------------------------------------------------------
    integer img_ptr, b, px, i, best, pred, gbest, gpred;
    reg [1023:0] vcdfile;

    initial begin
        if ($value$plusargs("images=%d", n_images)) ;
        if ($value$plusargs("batch=%d", batch_arg)) ;
        if (batch_arg < 1) batch_arg = 1;
        if (batch_arg > B_MAX) batch_arg = B_MAX;
        if ($value$plusargs("vcd=%s", vcdfile)) begin
            $dumpfile(vcdfile);
            $dumpvars(0, dut);
        end

        repeat (4) @(posedge clk);
        rst_n = 1;
        repeat (2) @(posedge clk);

        img_ptr = 0;
        while (img_ptr < n_images) begin
            nb = (n_images - img_ptr < batch_arg) ? n_images - img_ptr : batch_arg;
            batch_base = img_ptr;

            // load batch images through the image port
            for (b = 0; b < nb; b = b + 1)
                for (px = 0; px < 784; px = px + 1) begin
                    img_wen  <= 1;
                    img_b    <= b[B_ADDR-1:0];
                    img_idx  <= px[9:0];
                    img_data <= images[(batch_base + b)*784 + px];
                    @(posedge clk);
                end
            img_wen <= 0;

            if (tfh != 0) begin
                $fwrite(tfh, "{\"ev\":\"img\",\"label\":%0d,\"pix\":[", labels[batch_base]);
                for (px = 0; px < 784; px = px + 1)
                    $fwrite(tfh, "%s%0d", px == 0 ? "" : ",", images[batch_base*784 + px]);
                $fwrite(tfh, "]}\n");
            end

            batch_size <= nb[B_ADDR:0];
            @(posedge clk);
            start <= 1;
            @(posedge clk);
            start <= 0;
            // done is latched from the previous run; wait for it to clear
            // (start sampled) before waiting for this run's completion
            @(posedge clk);
            @(posedge clk);
            wait (done);
            @(posedge clk);

            if (nb == 1)     cov_batch_1   = cov_batch_1 + 1;
            if (nb == B_MAX) cov_batch_max = cov_batch_max + 1;
            runs = runs + 1;
            total_cycles = total_cycles + cycle_count;
            $display("CYCLES run=%0d batch=%0d cycles=%0d", runs, nb, cycle_count);

            // check this batch
            for (b = 0; b < nb; b = b + 1) begin
                best = -32'sd2147483647; pred = 0;
                gbest = -32'sd2147483647; gpred = 0;
                for (k = 0; k < 10; k = k + 1) begin
                    if (rtl_logits[b][k] !== exp_logits[(batch_base + b)*10 + k])
                        logit_errors = logit_errors + 1;
                    logit_checked = logit_checked + 1;
                    if (rtl_logits[b][k] > best) begin
                        best = rtl_logits[b][k]; pred = k;
                    end
                    if (exp_logits[(batch_base + b)*10 + k] > gbest) begin
                        gbest = exp_logits[(batch_base + b)*10 + k]; gpred = k;
                    end
                end
                results = results + 1;
                if (pred == labels[batch_base + b]) pred_match_label = pred_match_label + 1;
                if (pred == gpred)                  pred_match_golden = pred_match_golden + 1;
                $display("RESULT img=%0d pred=%0d label=%0d golden=%0d",
                         batch_base + b, pred, labels[batch_base + b], gpred);
            end
            img_ptr = img_ptr + nb;
        end

        $display("ACTCHECK errors=%0d checked=%0d", act_errors, act_checked);
        $display("LOGITCHECK errors=%0d checked=%0d", logit_errors, logit_checked);
        $display("PREDS total=%0d match_label=%0d match_golden=%0d",
                 results, pred_match_label, pred_match_golden);
        $display("TOTALCYCLES runs=%0d cycles=%0d", runs, total_cycles);
        report_coverage;
        if (act_errors == 0 && logit_errors == 0 && pred_match_golden == results)
            $display("TB PASS");
        else
            $display("TB FAIL");
        if (tfh != 0) $fclose(tfh);
        $finish;
    end

endmodule
